package com.finanest.annotations;

// Generated 09/12/2015 08:38:48 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Caixa generated by hbm2java
 */
@Entity
@Table(name = "CAIXA", catalog = "FinanEst")
public class Caixa implements java.io.Serializable {

	private Integer idCaixa;
	private String descricao;
	private Date data;
	private String historico;
	private String complemento;
	private Double entrada;
	private Double saida;
	private Double saldo;
	private Integer idFuncionario;

	public Caixa() {
	}

	public Caixa(String descricao, Date data, String historico,
			String complemento, Double entrada, Double saida, Double saldo,
			Integer idFuncionario) {
		this.descricao = descricao;
		this.data = data;
		this.historico = historico;
		this.complemento = complemento;
		this.entrada = entrada;
		this.saida = saida;
		this.saldo = saldo;
		this.idFuncionario = idFuncionario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCAIXA", unique = true, nullable = false)
	public Integer getIdCaixa() {
		return this.idCaixa;
	}

	public void setIdCaixa(Integer idCaixa) {
		this.idCaixa = idCaixa;
	}

	@Column(name = "DESCRICAO", length = 20)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA", length = 10)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Column(name = "HISTORICO", length = 30)
	public String getHistorico() {
		return this.historico;
	}

	public void setHistorico(String historico) {
		this.historico = historico;
	}

	@Column(name = "COMPLEMENTO", length = 20)
	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	@Column(name = "ENTRADA", precision = 22, scale = 0)
	public Double getEntrada() {
		return this.entrada;
	}

	public void setEntrada(Double entrada) {
		this.entrada = entrada;
	}

	@Column(name = "SAIDA", precision = 22, scale = 0)
	public Double getSaida() {
		return this.saida;
	}

	public void setSaida(Double saida) {
		this.saida = saida;
	}

	@Column(name = "SALDO", precision = 22, scale = 0)
	public Double getSaldo() {
		return this.saldo;
	}

	public void setSaldo(Double saldo) {
		this.saldo = saldo;
	}

	@Column(name = "idFUNCIONARIO")
	public Integer getIdFuncionario() {
		return this.idFuncionario;
	}

	public void setIdFuncionario(Integer idFuncionario) {
		this.idFuncionario = idFuncionario;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Caixa [idCaixa=" + idCaixa + ", descricao=" + descricao
				+ ", data=" + data + ", historico=" + historico
				+ ", complemento=" + complemento + ", entrada=" + entrada
				+ ", saida=" + saida + ", saldo=" + saldo + ", idFuncionario="
				+ idFuncionario + "]";
	}

}
