package com.finanest.annotations;

// Generated 09/12/2015 08:38:48 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Caixa generated by hbm2java
 */
@Entity
@Table(name = "CAIXA", catalog = "FinanEst")
@ManagedBean(name = "caixaBean", eager=true)
@RequestScoped
public class Caixa implements java.io.Serializable {
	
	@ManagedProperty(value="#{idCaixa}")
	private Integer idCaixa;
	@ManagedProperty(value="#{data}")
	private Date data;
	@ManagedProperty(value="#{historico}")
	private String historico;
	@ManagedProperty(value="#{complemento}")
	private String complemento;
	@ManagedProperty(value="#{entrada}")
	private Double entrada;
	@ManagedProperty(value="#{saida}")
	private Double saida;
	@ManagedProperty(value="#{saldo}")
	private Double saldo;
	@ManagedProperty(value="#{idFuncionario}")
	private Integer idFuncionario;
	@ManagedProperty(value="#{idPessoa}")
	private Integer idPessoa;
	@ManagedProperty(value="#{qtde}")
	private int qtde;
	@ManagedProperty(value="#{tipo}")
	private String tipo;
	@ManagedProperty(value="#{idEstoque}")
	private int idEstoque;

	public Caixa() {
	}

	public Caixa(Date data, Double entrada, Double saida, Integer idPessoa,
			int qtde, String tipo, int idEstoque) {
		super();
		this.data = data;
		this.entrada = entrada;
		this.saida = saida;
		this.idPessoa = idPessoa;
		this.qtde = qtde;
		this.tipo = tipo;
		this.idEstoque = idEstoque;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCAIXA", unique = true, nullable = false)
	public Integer getIdCaixa() {
		return this.idCaixa;
	}

	public void setIdCaixa(Integer idCaixa) {
		this.idCaixa = idCaixa;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA", length = 10)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Column(name = "HISTORICO", length = 30)
	public String getHistorico() {
		return this.historico;
	}

	public void setHistorico(String historico) {
		this.historico = historico;
	}

	@Column(name = "COMPLEMENTO", length = 20)
	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	@Column(name = "ENTRADA", precision = 22, scale = 0)
	public Double getEntrada() {
		return this.entrada;
	}

	public void setEntrada(Double entrada) {
		this.entrada = entrada;
	}

	@Column(name = "SAIDA", precision = 22, scale = 0)
	public Double getSaida() {
		return this.saida;
	}

	public void setSaida(Double saida) {
		this.saida = saida;
	}

	@Column(name = "SALDO", precision = 22, scale = 0)
	public Double getSaldo() {
		return this.saldo;
	}

	public void setSaldo(Double saldo) {
		this.saldo = saldo;
	}

	@Column(name = "idPESSOA")
	public Integer getIdPessoa() {
		return idPessoa;
	}

	public void setIdPessoa(Integer idPessoa) {
		this.idPessoa = idPessoa;
	}

	/**
	 * @return the qtde
	 */
	@Column(name = "QTDE")
	public int getQtde() {
		return qtde;
	}

	/**
	 * @param qtde the qtde to set
	 */
	public void setQtde(int qtde) {
		this.qtde = qtde;
	}

	/**
	 * @return the tipo
	 */
	@Column(name = "TIPO", length = 20)
	public String getTipo() {
		return tipo;
	}

	/**
	 * @param tipo the tipo to set
	 */
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	/**
	 * @return the idEstoque
	 */
	@Column(name = "idESTOQUE")
	public int getIdEstoque() {
		return idEstoque;
	}

	/**
	 * @param idEstoque the idEstoque to set
	 */
	public void setIdEstoque(int idEstoque) {
		this.idEstoque = idEstoque;
	}

	@Column(name = "idFUNCIONARIO")
	public Integer getIdFuncionario() {
		return this.idFuncionario;
	}

	public void setIdFuncionario(Integer idFuncionario) {
		this.idFuncionario = idFuncionario;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Caixa [idCaixa=" + idCaixa + ", data=" + data + ", historico="
				+ historico + ", complemento=" + complemento + ", entrada="
				+ entrada + ", saida=" + saida + ", saldo=" + saldo
				+ ", idFuncionario=" + idFuncionario + ", idPessoa=" + idPessoa
				+ ", qtde=" + qtde + ", tipo=" + tipo + ", idEstoque="
				+ idEstoque + "]";
	}

}
