package com.finanest.annotations;

// Generated 09/12/2015 08:38:48 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contato generated by hbm2java
 */
@Entity
@Table(name = "CONTATO", catalog = "FinanEst")
@ManagedBean(name = "contatoBean", eager=true)
@RequestScoped
public class Contato implements java.io.Serializable {

	@ManagedProperty(value="#{idContato}")
	private Integer idContato;
	@ManagedProperty(value="#{nome}")
	private String nome;
	@ManagedProperty(value="#{email}")
	private String email;
	@ManagedProperty(value="#{instituicao}")
	private String instituicao;
	@ManagedProperty(value="#{assunto}")
	private String assunto;
	@ManagedProperty(value="#{mensagem}")
	private String mensagem;
	@ManagedProperty(value="#{data}")
	private Date data;

	public Contato() {
	}

	public Contato(String nome, String email, String instituicao,
			String assunto, String mensagem, Date data) {
		this.nome = nome;
		this.email = email;
		this.instituicao = instituicao;
		this.assunto = assunto;
		this.mensagem = mensagem;
		this.data = data;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCONTATO", unique = true, nullable = false)
	public Integer getIdContato() {
		return this.idContato;
	}

	public void setIdContato(Integer idContato) {
		this.idContato = idContato;
	}

	@Column(name = "NOME", length = 20)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "EMAIL", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "INSTITUICAO", length = 30)
	public String getInstituicao() {
		return this.instituicao;
	}

	public void setInstituicao(String instituicao) {
		this.instituicao = instituicao;
	}

	@Column(name = "ASSUNTO", length = 15)
	public String getAssunto() {
		return this.assunto;
	}

	public void setAssunto(String assunto) {
		this.assunto = assunto;
	}

	@Column(name = "MENSAGEM", length = 65535)
	public String getMensagem() {
		return this.mensagem;
	}

	public void setMensagem(String mensagem) {
		this.mensagem = mensagem;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA", length = 10)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Contato [idContato=" + idContato + ", nome=" + nome
				+ ", email=" + email + ", instituicao=" + instituicao
				+ ", assunto=" + assunto + ", mensagem=" + mensagem + ", data="
				+ data + "]";
	}

}
