package com.finanest.annotations;

// Generated 09/12/2015 08:38:48 by Hibernate Tools 4.3.1

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Funcionario generated by hbm2java
 */
@Entity
@Table(name = "FUNCIONARIO", catalog = "FinanEst")
@ManagedBean(name = "funcionarioBean", eager=true)
@RequestScoped
public class Funcionario implements java.io.Serializable {

	@ManagedProperty(value="#{idFuncionario}")
	private Integer idFuncionario;
	@ManagedProperty(value="#{nome}")
	private String nome;
	@ManagedProperty(value="#{cpf}")
	private String cpf;
	@ManagedProperty(value="#{senha}")
	private String senha;
	@ManagedProperty(value="#{endereco}")
	private String endereco;
	@ManagedProperty(value="#{foneprn}")
	private String foneprn;
	@ManagedProperty(value="#{fonesec}")
	private String fonesec;
	@ManagedProperty(value="#{email}")
	private String email;
	@ManagedProperty(value="#{salario}")
	private Double salario;

	public Funcionario() {
	}

	public Funcionario(String nome, String cpf, String senha, String endereco,
			String foneprn, String fonesec, String email, Double salario) {
		this.nome = nome;
		this.cpf = cpf;
		this.senha = senha;
		this.endereco = endereco;
		this.foneprn = foneprn;
		this.fonesec = fonesec;
		this.email = email;
		this.salario = salario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFUNCIONARIO", unique = true, nullable = false)
	public Integer getIdFuncionario() {
		return this.idFuncionario;
	}

	public void setIdFuncionario(Integer idFuncionario) {
		this.idFuncionario = idFuncionario;
	}

	@Column(name = "NOME", length = 20)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "CPF", length = 20)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Column(name = "SENHA", length = 20)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@Column(name = "ENDERECO", length = 40)
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "FONEPRN", length = 20)
	public String getFoneprn() {
		return this.foneprn;
	}

	public void setFoneprn(String foneprn) {
		this.foneprn = foneprn;
	}

	@Column(name = "FONESEC", length = 20)
	public String getFonesec() {
		return this.fonesec;
	}

	public void setFonesec(String fonesec) {
		this.fonesec = fonesec;
	}

	@Column(name = "EMAIL", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "SALARIO", precision = 22, scale = 0)
	public Double getSalario() {
		return this.salario;
	}

	public void setSalario(Double salario) {
		this.salario = salario;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Funcionario [idFuncionario=" + idFuncionario + ", nome=" + nome
				+ ", cpf=" + cpf + ", senha=" + senha + ", endereco="
				+ endereco + ", foneprn=" + foneprn + ", fonesec=" + fonesec
				+ ", email=" + email + ", salario=" + salario + "]";
	}

}
