package com.finanest.annotations;

// Generated 09/12/2015 08:38:48 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "USUARIO", catalog = "FinanEst")
@ManagedBean(name = "usuBean", eager=true)
@RequestScoped
public class Usuario implements java.io.Serializable {

	@ManagedProperty(value="#{idUsuario}")
	private Integer idUsuario;
	@ManagedProperty(value="#{nome}")
	private String nome;
	@ManagedProperty(value="#{senha}")
	protected String senha;
	@ManagedProperty(value="#{email}")
	protected String email;
	@ManagedProperty(value="#{fone}")
	private String fone;

	public Usuario() {
	}

	public Usuario(String nome, String senha, String email, String fone) {
		this.nome = nome;
		this.senha = senha;
		this.email = email;
		this.fone = fone;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUSUARIO", unique = true, nullable = false)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "NOME", length = 20)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "SENHA", length = 20)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@Column(name = "EMAIL", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "FONE", length = 15)
	public String getFone() {
		return this.fone;
	}

	public void setFone(String fone) {
		this.fone = fone;
	}
	
	public String verificarLogin() {
		Contato contato = new Contato();
		
		if(this.email.equalsIgnoreCase("root") && this.senha.equalsIgnoreCase("ufersa")) {
			System.out.println("OK");
			
			
//			List<Usuario> listaUsuarios = daoUsuario.listar();

			return "index";
		}
		else {
			System.out.println("Erro...");
			return "login";
		}
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Usuario [idUsuario=" + idUsuario + ", nome=" + nome
				+ ", senha=" + senha + ", email=" + email + ", fone=" + fone
				+ "]";
	}

}
