-- use FinanEst;
-- drop table USUARIO;
-- drop table FUNCIONARIO;
-- drop table FORNECEDOR;
-- drop table ESTOQUE;
-- drop table CLIENTE;
-- drop table CAIXA;
-- drop table CONTATO;

CREATE TABLE USUARIO (
    idUSUARIO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(20),
    SENHA VARCHAR(20),
    EMAIL VARCHAR(30),
    FONE VARCHAR(15),
    PRIMARY KEY (idUSUARIO)
)  AUTO_INCREMENT=1;

CREATE TABLE FUNCIONARIO (
    idFUNCIONARIO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(20),
    CPF VARCHAR(20),
    SENHA VARCHAR(20),
    ENDERECO VARCHAR(40),
    FONEPRN VARCHAR(20),
    FONESEC VARCHAR(20),
    EMAIL VARCHAR(30),
    SALARIO DOUBLE,
    PRIMARY KEY (idFUNCIONARIO)
)  AUTO_INCREMENT=1;

CREATE TABLE FORNECEDOR (
    idFORNECEDOR INT NOT NULL AUTO_INCREMENT,
    RZSOCIAL VARCHAR(20),
    NMFANTASIA VARCHAR(20),
    CNPJ VARCHAR(20),
    ENDERECO VARCHAR(40),
    FONEPRN VARCHAR(20),
    FONESEC VARCHAR(20),
    EMAIL VARCHAR(30),
    SITE VARCHAR(30),
    PRIMARY KEY (idFORNECEDOR)
)  AUTO_INCREMENT=1;

CREATE TABLE CLIENTE (
    idCLIENTE INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(20),
    CPF VARCHAR(20),
    SENHA VARCHAR(20),
    ENDERECO VARCHAR(40),
    FONEPRN VARCHAR(20),
    FONESEC VARCHAR(20),
    EMAIL VARCHAR(30),
    PRIMARY KEY (idCLIENTE)
)  AUTO_INCREMENT=1;

CREATE TABLE ESTOQUE (
    idESTOQUE INT NOT NULL AUTO_INCREMENT,
    TIPO VARCHAR(20),
    INSUMO VARCHAR(30),
    PRECO FLOAT,
    QTDE INT,
    DATA DATE,
    idFORNECEDOR INT REFERENCES FORNECEDOR (idFORNECEDOR),
    idFUNCIONARIO INT REFERENCES FUNCIONARIO (idFUNCIONARIO),
    PRIMARY KEY (idESTOQUE)
)  AUTO_INCREMENT=1;

CREATE TABLE CAIXA (
    idCAIXA INT NOT NULL AUTO_INCREMENT,
    DESCRICAO VARCHAR(20),
    DATA DATE,
    HISTORICO VARCHAR(30),
    COMPLEMENTO VARCHAR(20),
    ENTRADA DOUBLE,
    SAIDA DOUBLE,
    SALDO DOUBLE,
    idFUNCIONARIO INT REFERENCES FUNCIONARIO (idFUNCIONARIO),
    PRIMARY KEY (idCAIXA)
)  AUTO_INCREMENT=1;

CREATE TABLE CONTATO (
    idCONTATO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(20),
    EMAIL VARCHAR(30),
    INSTITUICAO VARCHAR(30),
    ASSUNTO VARCHAR(10),
    MENSAGEM TEXT,
	DATA DATE,
    PRIMARY KEY (idCONTATO)
)  AUTO_INCREMENT=1;